apiVersion: gateway.k8s.aws/v1
kind: LoadBalancerConfiguration
metadata:
  name: flipkart-alb
  namespace: flipkart
spec:
  scheme: internet-facing
  ipAddressType: ipv4
  listenerConfigurations:
  - protocolPort: HTTPS:443
    certificates:
    - arn:aws:acm:us-east-1:129678139522:certificate/e3e72c65-449c-46f7-8192-71adc4b1c5d3

# We are going to use ALB, Listener