apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: flipkart
  labels:
    project: flipkart
    tier: db
    component: mongodb
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    project: flipkart
    tier: db
    component: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: flipkart
  labels:
    project: flipkart
    tier: db
    component: mongodb
spec: 
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    project: flipkart
    tier: db
    component: mongodb