apiVersion: v1
kind: Service
metadata: 
  name: headless-mysql
  namespace: flipkart
  labels:
    project: flipkart
    tier: db
    component: mysql
spec:
  clusterIP: None
  selector:
    project: flipkart
    tier: db
    component: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: flipkart
  labels:
    project: flipkart
    tier: db
    component: mysql
spec:
  selector:
    project: flipkart
    tier: db
    component: mysql
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # container port
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: flipkart
type: Opaque
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "eWVzCg=="
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: flipkart
  labels:
    project: flipkart
    tier: db
    component: mysql
spec:
  serviceName: headless-mysql
  replicas: 1
  selector:
    matchLabels:
      project: flipkart
      tier: db
      component: mysql
  # Pod
  template:
    metadata:
      labels:
        project: flipkart
        tier: db
        component: mysql
    spec: 
      containers:
      - name: mysql
        image: sudhakar20000/mysql:v1
        args: ["--mysql-native-password=ON"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "RoboShop@1"
        volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
  # PVC
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "flipkart-ebs"
      resources:
        requests:
          storage: 1Gi  
