apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: flipkart
  labels:
    project: flipkart
    tier: frontend
    component: frontend
spec:
  type: LoadBalancer
  selector:
    project: flipkart
    tier: frontend
    component: frontend
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port