apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: flipkart

type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.secret.rabbitmq_username }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secret.rabbitmq_password }}